#! /bin/sh

# XDG base dirs (set if unset or null)
export XDG_DATA_HOME=${XDG_DATA_HOME:-"$HOME/.local/share"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-"$HOME/.cache"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME/.config"}

# Xorg
export XAUTHORITY="$XDG_RUNTIME_DIR/xauthority"
export XINITRC="$XDG_CONFIG_HOME/xorg/initrc"

# XMonad
export XMONAD_CONFIG_DIR="$XDG_CONFIG_HOME/xmonad"
export XMONAD_CACHE_DIR="$XDG_CACHE_HOME/xmonad"
export XMONAD_DATA_DIR="$XDG_DATA_HOME/xmonad"

# Util
export LESSHISTFILE="$HOME/.cache/lesshist"

# Compiler and packagers
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
